### ISSUE TITLE
Get stuck on Windows with pnpm

### ISSUE THREAD

**Issue by meteorlxy** [cyco130/eslint-import-resolver-exports#1]
```sh
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
    Memory: 666.18 MB / 15.73 GB
  Binaries:
    Node: 16.15.0
    PNPM: 7.9.0
  Packages:
    eslint: 8.22.0
    eslint-plugin-import: 2.26.0
    eslint-import-resolver-exports: 1.0.0-beta.2
```

This import resolver made eslint got stuck on Windows (perhaps also related to pnpm).

With following debug error:

![image](https://user-images.githubusercontent.com/18205362/185017064-94e3ace7-13f6-4acb-8fb2-8928aa76dfeb.png)

FYI, it works well on Linux and MacOS

**Comment by cyco130** [comment]
Sorry for the late response, I somehow missed this :/ I added Windows support in `beta.3`, please drop a line if it doesn't fix your problem.
